<script lang="ts">
 import { base } from '$app/paths';
 import { ArrowUpRight, Store, ArrowRight } from '@lucide/svelte';
 import { locale, tr, market, currencyLabel, groupName as groupLabel } from './i18n.svelte';
 import { catalog, fmtPrice } from '$lib/data.svelte';
 import { matchingPrice, matchingOffers, type ProductFilters } from '$lib/search';
 import CategoryIcon from './CategoryIcon.svelte';
 import type { Product } from '$lib/parquet';
 let { product, offerFilters = {} }: { product:Product; offerFilters?:ProductFilters } = $props();
 let name = $derived(locale.language === 'ar' && product.canonical_name_ar ? product.canonical_name_ar : product.canonical_name);
 let stats = $derived(catalog.stats.get(product.id));
 let filters = $derived({ currency:market.profile.currency, ...offerFilters });
 let price = $derived(matchingPrice(stats,filters));
 let offers = $derived(matchingOffers(stats,filters));
 let stocked = $derived(stats?.current_offers !== undefined ? offers.some(o => o.availability==='in_stock') : (stats?.in_stock_sellers ?? 0)>0);
 let availability = $derived(stocked ? tr('In stock','متوفر') : offers.some(o => o.availability==='preorder') ? tr('Preorder','طلب مسبق') : offers.length && offers.every(o => o.availability==='out_of_stock') ? tr('Out of stock','غير متوفر') : tr('Check availability','راجع التوفر'));
 let currentSellers = $derived(stats?.current_offers !== undefined ? new Set(offers.map(o => o.seller)).size : product.sellers.length);
 let imageFailed = $state(false);
 $effect(() => { void product.image; imageFailed = false; });
 let src = $derived(product.image && /^https?:\/\//i.test(product.image) ? product.image : null);
</script>
<a class="card item" href="{base}/product/{encodeURIComponent(product.id)}/" aria-label="{name}, {price != null ? fmtPrice(price,filters.currency) : tr('price unavailable','السعر غير متاح')}, {tr('compare offers','قارن العروض')}">
 <div class="product-media"><span class="part-category">{groupLabel(product.group)}</span>{#if src && !imageFailed}<img src={src} alt="" loading="lazy" decoding="async" onerror={() => imageFailed = true}/>{:else}<div class="placeholder"><CategoryIcon group={product.group} size={56}/><span>{product.brand || 'COMPONENT'}</span></div>{/if}<span class="image-arrow"><ArrowUpRight size={16}/></span></div>
 <div class="body"><div class="product-brand">{product.brand || groupLabel(product.group)}</div><h3 dir="auto">{name}</h3><div class="availability" class:stocked><span></span>{availability}</div><div class="pricing"><span class="price-label">{offerFilters.inStock ? tr('Lowest in-stock price','أقل سعر متوفر') : offerFilters.seller ? tr('Selected store price','السعر في المحل المحدد') : tr('Lowest listed price','أقل سعر مسجل')}</span><div class="price">{#if price != null}<span class="currency">{currencyLabel(filters.currency)}</span><strong>{fmtPrice(price,'').trim()}</strong>{:else}<strong class="unpriced">{tr('Check with seller','راجع المحل')}</strong>{/if}</div></div><div class="card-bottom"><span><Store size={13}/>{currentSellers || product.sellers.length} {currentSellers===1 || (!currentSellers && product.sellers.length===1) ? tr('store','محل') : tr('stores','محلات')}</span><span class="compare">{tr('Compare','قارن')}<ArrowRight size={13}/></span></div></div>
</a>
<style>
 .item { display:flex; flex-direction:column; overflow:hidden; transition:transform .18s,border-color .18s,box-shadow .18s; border-radius:12px; box-shadow:0 2px 4px #172b3a02; }.item:hover { border-color:#9fcabe; box-shadow:0 8px 24px #173e3510; transform:translateY(-3px); }.product-media { position:relative; height:174px; display:grid; place-items:center; background:#fff; margin:8px 8px 0; border-radius:8px; overflow:hidden; }.product-media img { position:absolute; inset:0; width:100%; height:100%; padding:4px; object-fit:contain; object-position:center; }.part-category { position:absolute; top:5px; inset-inline-start:5px; z-index:1; background:#f4f6f6ee; color:#657b72; border-radius:4px; padding:3px 6px; font-size:.75rem; font-weight:500; }.image-arrow { position:absolute; bottom:8px; inset-inline-end:8px; color:#8d9a96; opacity:0; transition:opacity .2s; }.item:hover .image-arrow { opacity:1; }.placeholder { color:#94b3a7; display:flex; align-items:center; flex-direction:column; justify-content:center; gap:12px; background:radial-gradient(circle,#edf5f0,white 70%); width:100%; height:100%; }.placeholder span { color:#97a69f; font-size:.75rem; letter-spacing:2px; }.body { padding:15px 16px 0; display:flex; flex-direction:column; flex:1; }.product-brand { color:#8b969e; font-size:.75rem; letter-spacing:1.2px; text-transform:uppercase; margin-bottom:7px; overflow:hidden; white-space:nowrap; text-overflow:ellipsis; }.body h3 { font-size:.9375rem; line-height:1.5; font-weight:600; display:-webkit-box; -webkit-line-clamp:2; line-clamp:2; -webkit-box-orient:vertical; overflow:hidden; min-height:3em; overflow-wrap:anywhere; }.availability { display:flex; align-items:center; gap:5px; font-size:.75rem; color:#8c7765; margin-top:8px; }.availability>span { width:5px; height:5px; border-radius:50%; background:#b69c83; }.availability.stocked { color:#45835f; }.availability.stocked>span { background:#4a9468; }.pricing { margin-top:14px; margin-bottom:14px; }.price-label { font-size:.75rem; color:#8c969e; }.price { display:flex; align-items:baseline; gap:5px; margin-top:1px; }.price strong { font-size:1.4375rem; letter-spacing:-.7px; font-weight:650; font-variant-numeric:tabular-nums; }.currency { font-size:.8125rem; color:var(--muted); }.price strong.unpriced { font-size:1.125rem; letter-spacing:0; }.card-bottom { display:flex; justify-content:space-between; align-items:center; gap:6px; border-top:1px solid #edf0f2; padding:11px 0; font-size:.75rem; color:#809088; margin-top:auto; }.card-bottom>span { display:flex; align-items:center; gap:5px; }.card-bottom .compare { font-weight:600; color:var(--accent); }
 @media(max-width:600px) { .product-media { height:140px; margin:5px 5px 0; }.product-media img { padding:3px; object-position:center center; }.body { padding:12px 11px 0; }.body h3 { font-size:.875rem; }.price strong { font-size:1.3125rem; }.card-bottom { font-size:.75rem; }.part-category { font-size:.75rem; }.pricing { margin-top:10px; margin-bottom:10px; }.availability { font-size:.75rem; } }
</style>
